
var sentimentCache=null;
function loadSentimentData(){fetch('sentiment_summary.json?v='+Date.now()).then(function(r){return r.json()}).then(function(data){sentimentCache=data;renderSentimentKPIs(data);renderSentimentTrend(data);renderSentimentNegList(data);renderSentimentItems(data);updateOverviewSentiment(data);updateSentimentBadge(data);}).catch(function(){});}
function refreshSentimentLive(){toast('🔄 正在刷新数据...');loadSentimentData();setTimeout(function(){if(sentimentCache)toast('✅ 已更新 ('+sentimentCache.today.total+'条)');},1000);}
function renderSentimentKPIs(data){var t=data.today;var h='<div class="kpi accent-green"><div class="kpi-label">📊 今日舆情总量</div><div class="kpi-value">'+t.total+'<span class="kpi-change flat">条</span></div><div class="kpi-sub">'+data.latest_date+'</div></div>'+'<div class="kpi accent-teal"><div class="kpi-label">😊 正面</div><div class="kpi-value">'+t.pos+'<span class="kpi-change up">'+(t.pos_pct||0).toFixed(0)+'%</span></div><div class="kpi-sub">口碑健康</div></div>'+'<div class="kpi '+(t.neg>0?'accent-red':'accent-green')+'"><div class="kpi-label">⚠️ 负面</div><div class="kpi-value">'+t.neg+'<span class="kpi-change '+(t.neg>0?'down':'flat')+'">'+(t.neg>0?'需关注':'✅')+'</span></div><div class="kpi-sub">近7天累计 '+data.last_7d.neg+' 条</div></div>'+'<div class="kpi accent-blue"><div class="kpi-label">📊 7天总量</div><div class="kpi-value">'+data.last_7d.total+'<span class="kpi-change flat">条</span></div><div class="kpi-sub">'+data.daily_trend[0].date+' ~ '+data.daily_trend[data.daily_trend.length-1].date+'</div></div>';document.getElementById('sentimentKPI').innerHTML=h;document.getElementById('sentimentMeta').textContent='数据源: master_data.json ('+data.date_range+')';}
function renderSentimentTrend(data){var trend=data.daily_trend;var ctx=document.getElementById('sentimentTrendChart');if(!ctx)return;new Chart(ctx,{type:'line',data:{labels:trend.map(function(d){return d.date.slice(5)}),datasets:[{label:'总量',data:trend.map(function(d){return d.total}),borderColor:'#2d8a4e',backgroundColor:'rgba(45,138,78,.1)',borderWidth:2,pointRadius:3,fill:true,tension:.3},{label:'正面',data:trend.map(function(d){return d.pos}),borderColor:'#4caf50',borderWidth:1.5,pointRadius:2,tension:.3,borderDash:[3,2]},{label:'负面',data:trend.map(function(d){return d.neg}),borderColor:'#e53935',borderWidth:1.5,pointRadius:3,pointBackgroundColor:'#e53935',tension:.3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{usePointStyle:true,boxWidth:6,font:{size:10}}}},scales:{x:{ticks:{font:{size:10}},grid:{display:false}},y:{beginAtZero:true,ticks:{font:{size:10}},grid:{color:'#e8ece8'}}}}});}
var sentimentFilter='all';
function filterSentimentItems(filter){sentimentFilter=filter;['all','pos','neg'].forEach(function(f){var btn=document.getElementById('sentFilter'+f.charAt(0).toUpperCase()+f.slice(1));if(btn){btn.classList.remove('btn-primary','btn-ghost');btn.classList.add(filter===f?'btn-primary':'btn-ghost');}});if(sentimentCache)renderSentimentItems(sentimentCache);}
function renderSentimentItems(data){var allItems=data.today_items||[];var items;if(sentimentFilter==='pos')items=allItems.filter(function(i){return i.sentiment==='pos'});else if(sentimentFilter==='neg')items=allItems.filter(function(i){return i.sentiment==='neg'});else items=allItems;document.getElementById('sentimentItemCount').textContent=items.length;document.getElementById('sentimentItemTime').textContent=data.generated;var list=document.getElementById('sentimentItemsList');if(items.length===0){list.innerHTML='<div style="text-align:center;padding:20px;color:var(--text-dim)">暂无明细数据</div>';return;}var emoji={pos:'😊',neg:'🔴',neu:'➖'};var html='';items.forEach(function(item){var s=item.sentiment||'';html+='<div style="padding:6px 0;border-bottom:1px solid var(--border);display:flex;gap:8px;align-items:flex-start"><span style="font-size:16px;flex-shrink:0">'+(emoji[s]||'📌')+'</span><div style="flex:1;min-width:0"><div style="font-weight:600;color:var(--text)">'+item.title+'</div><div style="font-size:11px;color:var(--text-dim)">'+item.platform+' · '+item.author+' · '+(item.category||'')+'</div></div>'+(item.url?'<a href="'+item.url+'" target="_blank" style="font-size:11px;color:var(--brand);flex-shrink:0;text-decoration:none">原帖 ↗</a>':'')+'<span onclick="quickStar(this)" data-date="'+item.date+'" data-title="'+item.title.replace(/"/g,'&quot;')+'" data-platform="'+item.platform+'" data-author="'+(item.author||'')+'" data-url="'+(item.url||'')+'" class="star-btn'+(isStarred(item.date,item.title)?' active':'')+'" title="收藏/取消">⭐</span></div>';});list.innerHTML=html;}
function renderSentimentNegList(data){var items=data.negative_items;items.sort(function(a,b){return b.date.localeCompare(a.date)});var list=document.getElementById('sentimentNegList');if(items.length===0){list.innerHTML='<div style="text-align:center;padding:40px;color:var(--text-dim)">✅ 近7天无负面舆情</div>';return;}var html='';items.slice(0,15).forEach(function(item){html+='<div style="padding:8px 0;border-bottom:1px solid var(--border)"><div style="font-weight:600;color:var(--text);margin-bottom:2px">['+item.platform+'] '+item.title+'</div><div style="font-size:11px;color:var(--text-dim)">'+item.date+' · '+(item.category||'')+(item.url?' · <a href="'+item.url+'" target="_blank" style="color:var(--brand);text-decoration:none">原帖 ↗</a>':'')+'</div></div>';});list.innerHTML=html;}
function updateOverviewSentiment(data){var cards=document.querySelectorAll('#page-overview .kpi');if(cards.length>=1){var c1=cards[0];c1.querySelector('.kpi-value').innerHTML=data.today.total+'<span class="kpi-change flat">条</span>';c1.querySelector('.kpi-sub').textContent=data.latest_date+' · 正面'+data.today.pos+' · 负面'+data.today.neg;}}
function updateSentimentBadge(data){var b=document.getElementById('sentimentBadge');if(data.today.neg>0){b.textContent=data.today.neg;b.classList.add('show');}else if(data.last_7d.neg>0){b.textContent='!';b.classList.add('show');}}
